### ISSUE TITLE
Convert models with material scripts

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-sim#10]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/10)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
# Summary

Models that contain <material><script> tags currently do not work with Ogre1, and may never work with ogre2.  For example see https://app.ignitionrobotics.org/openrobotics/fuel/models/Textured%20Shapes

# Motivation

It would be nice to support automatic conversion of old scripts to new scripts. Not sure if this is feasible.

**Comment by azeey** [comment]
The current plan is to incorporate the Material parser from https://github.com/osrf/gzweb/blob/master/gzbridge/OgreMaterialParser.cc into `gz-sim` to parse the default `gazebo.material` script so that material names for solid colors, such as `Gazebo/Red` can be supported. i.e, The first step would be to parse `diffuse`, `ambient`, `emisive`, and `specular` values from the material script. In the future, we might add support for textures and `.material` script files provided by users.

Note that The `gazebo.material` script will have to be installed with `gz-sim`. 

cc @iche033
