### ISSUE TITLE
`pose_publisher` example does not work ootb due to specified world plugins

### ISSUE THREAD

**Issue by jrutgeer** [gazebosim/gz-sim#2048]
For the `pose_publisher` example world to work, I need to remove following lines (or all world plugins, line 5 till 16):

https://github.com/gazebosim/gz-sim/blob/50a99e6c2c102c54471e6ba364ba73d73c428696/test/worlds/pose_publisher.sdf#L9-L16

Else, it just shows an empty screen:

![image](https://github.com/gazebosim/gz-sim/assets/74099146/25d3da63-ba9c-4670-9d76-b05a4c6ed7b2)

I think it has something to do with mandatory plugins being loaded by default if none are specified, but no extra plugins loaded as soon as one is specified. I.e. if one plugin is specified but other (mandatory ones) aren't, then they will not be loaded.

Afaik there's no error message, and no clear documentation on this.

**Comment by jrutgeer** [comment]
I just realized that there's a `gz-sim/test/worlds/` folder as well as a `gz-sim/examples/worlds/` folder, but still I think each provided sdf should work ootb.

**Comment by azeey** [comment]
The worlds in the `test` directory are not examples. They are meant to be used by tests and in this instance, the test didn't need the `SceneBroadcaster` system, which is why the GUI doesn't work. If this issue is also present in the `examples` directory, we need to fix it, but for the test world, I don't think there's anything to fix.
