### ISSUE TITLE
Regression in Resource Spawner in Harmonic

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-sim#2486]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? Binary, 8.5.0

## Description
* Expected behavior: Resource spawner to work
* Actual behavior: Clicking on any of the models to download them fails with the error `[GUI] [Wrn] [ResourceSpawner.cc:589] Download failed.  Try again.`. Trying to spawn the model fails with the error 
```
Error [SDF.cc:165] Tried to use callback in sdf::findFile(), but the callback is empty.  Did you call sdf::setFindCallback()?
[GUI] [Wrn] [Spawn.cc:381] Only model or light entities can be spawned at the moment.
```

I bisected gz-fuel-tools and found that the regression started in https://github.com/gazebosim/gz-fuel-tools/pull/376

## Steps to reproduce

1. `gz sim -v4 empty.sdf`
2. Add the `ResourceSpawner` gui plugin
3. Try to download or spawn any model

**Comment by mjcarroll** [comment]
I have managed to reproduce and bisect to the same location.  Working on a fix now.

**Comment by Safin-Sadman** [comment]
### Environment

* Ubuntu 24.04
* Gazebo Sim 8.11.0 (Harmonic)

### Steps to reproduce

1. Launch an empty world:

   ```bash
   gz sim empty.sdf
   ```
2. Open the **Resource Spawner** plugin.
3. Search for the official Open Robotics **Spectrum Plane** model.
4. Download the model.
5. Click **Spawn**.

### Expected behavior

The model is inserted into the world.

### Actual behavior

The model is not spawned. The console reports:

```text
Error [Utils.cc:176] Tried to use callback in sdf::findFile(), but the callback is empty.
Did you call sdf::setFindCallback()?
```

### Additional observations

I tested several official Fuel models using the same workflow:

* ✅ Breakfast Menu Original
* ✅ Construction Barrel
* ✅ Coke Can
* ✅ Office Chair
* ✅ Pioneer3AT (spawns, but reports a missing `libSkidSteerDrivePlugin.so`)
* ❌ Spectrum Plane (does not spawn)

This appears to be specific to the Spectrum Plane model or its interaction with the Resource Spawner, rather than a general Resource Spawner failure.

**Comment by azeey** [comment]
This is a closed issue. Could you please create a new one?

**Comment by Safin-Sadman** [comment]
> This is a closed issue. Could you please create a new one?

Created a new issue https://github.com/gazebosim/gz-sim/issues/3754
